baseURL = 'https://ifac.si/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'ifac.si — Sistemas para Internet'
theme = 'mainroad'

[params]
  copyright = 'Gustavo Cardial'
  customCSS = ["/css/dropdown.css", "/css/tables.css"]
  mainSections = ["posts"]
  description = "Portal informativo independente sobre o curso de Sistemas para Internet do IFAC — Campus Rio Branco. Horários, calendário, documentos, informações acadêmicas e conteúdos sobre computação."
  opengraph = true
  schema = true

[author]
  name = 'Gustavo Cardial'

[params.logo]
  title = 'ifac<span style="color:#e22d30">.</span>si — Sistemas para Internet'
  subtitle = 'Portal informativo independente sobre o curso'

[params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "taglist"]

[params.widgets]
  recent_num = 5

[params.style.vars]
  highlightColor = '#3fa14c'

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

[[menu.main]]
  name = "O curso"
  url = "/curso/"
  weight = 2

[[menu.main]]
  name = "Matriz curricular"
  url = "/curso/matriz-curricular/"
  parent = "O curso"
  weight = 1

[[menu.main]]
  name = "Documentos"
  url = "/documentos/"
  weight = 3

[[menu.main]]
  name = "Colegiado"
  url = "/documentos/colegiado/"
  parent = "Documentos"
  weight = 1

[[menu.main]]
  name = "Horários"
  url = "/horarios/"
  weight = 4

[[menu.main]]
  name = "Calendário"
  url = "/calendario/"
  weight = 5

[[menu.main]]
  name = "Suap"
  url = "https://suap.ifac.edu.br/"
  weight = 6

[[menu.main]]
  name = "Sobre"
  url = "/sobre/"
  weight = 7
